services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} # Using service name 'db' as host
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT} # Using service name 'redis' as host
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_FETCH_PORT: ${MINIO_FETCH_PORT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SSL: ${MINIO_SSL}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    env_file:
      - .env

  db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - .env
  redis:
    image: redis:7.4-alpine
    restart: always
    volumes:
      - redis-data:/var/lib/redis/data
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    hostname: minio
    command: server /data --console-address ":9001"
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_FETCH_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    env_file:
      - .env

volumes:
  db-data:
  redis-data:
  minio-data:


