name: CI

on:
  push:
    branches: ['dev']

  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Push Docker image
        run: docker compose up -d --force-recreate
        env:
          MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ vars.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ vars.MINIO_SECRET_KEY }}
          MINIO_PORT: ${{ vars.MINIO_PORT}}
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          MINIO_FETCH_PORT: ${{ vars.MINIO_FETCH_PORT }}
          MINIO_SSL: ${{ vars.MINIO_SSL }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          MINIO_ROOT_PASSWORD: ${{ vars.MINIO_ROOT_PASSWORD }}
          MINIO_ROOT_USER: ${{ vars.MINIO_ROOT_USER }}
