name: CI

on:
  push:
    branches: ['dev']

  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Push Docker image
        run: docker compose up -d
        env:
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_PORT: ${{ secrets.MINIO_PORT}}
