# name: CI

# on:
#   push:
#     branches: ['dev']

#   pull_request:
#     branches: ['dev']

# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - uses: actions/checkout@v4

#       - name: Create .env file
#         run: |
#           echo "MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}"  >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_PORT=${{ secrets.MINIO_PORT }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_FETCH_PORT=${{ secrets.MINIO_FETCH_PORT }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_SSL=${{ secrets.MINIO_SSL }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> /root/actions-runner/dh/dh-api/dh-api/.env
#           echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> /root/actions-runner/dh/dh-api/dh-api/.env

#       - name: Build Docker image
#         run: docker build -t my-image:latest .

#       - name: Start Docker image
#         run: docker compose up -d --force-recreate
#         env:
#           MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
#           MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
#           MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
#           MINIO_PORT: ${{ secrets.MINIO_PORT}}
#           REDIS_HOST: ${{ secrets.REDIS_HOST }}
#           REDIS_PORT: ${{ secrets.REDIS_PORT }}
#           MINIO_FETCH_PORT: ${{ secrets.MINIO_FETCH_PORT }}
#           MINIO_SSL: ${{ secrets.MINIO_SSL }}
#           NODE_ENV: ${{ secrets.NODE_ENV }}
#           POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#           POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#           POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#           MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
#           MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
